export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const USED_PRODUCT = "USED_PRODUCT";
export const MAYOR_PRECIO = "MAYOR_PRECIO";
export const MENOR_PRECIO = "MENOR_PRECIO";
export const PAGINACION = "PAGINACION";
export const PAGINACION_MENOS = "PAGINACION_MENOS";
